/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/offline/': RouteRecordInfo<'/offline/', '/offline', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/20220102': RouteRecordInfo<'/posts/20220102', '/posts/20220102', Record<never, never>, Record<never, never>>,
    '/posts/20220307': RouteRecordInfo<'/posts/20220307', '/posts/20220307', Record<never, never>, Record<never, never>>,
    '/posts/20220604': RouteRecordInfo<'/posts/20220604', '/posts/20220604', Record<never, never>, Record<never, never>>,
    '/posts/20220617': RouteRecordInfo<'/posts/20220617', '/posts/20220617', Record<never, never>, Record<never, never>>,
    '/posts/20220802': RouteRecordInfo<'/posts/20220802', '/posts/20220802', Record<never, never>, Record<never, never>>,
    '/posts/20221231': RouteRecordInfo<'/posts/20221231', '/posts/20221231', Record<never, never>, Record<never, never>>,
    '/posts/20230219': RouteRecordInfo<'/posts/20230219', '/posts/20230219', Record<never, never>, Record<never, never>>,
    '/posts/20230705': RouteRecordInfo<'/posts/20230705', '/posts/20230705', Record<never, never>, Record<never, never>>,
    '/posts/20241110': RouteRecordInfo<'/posts/20241110', '/posts/20241110', Record<never, never>, Record<never, never>>,
    '/posts/20250101': RouteRecordInfo<'/posts/20250101', '/posts/20250101', Record<never, never>, Record<never, never>>,
    '/posts/20250211': RouteRecordInfo<'/posts/20250211', '/posts/20250211', Record<never, never>, Record<never, never>>,
    '/posts/20250610': RouteRecordInfo<'/posts/20250610', '/posts/20250610', Record<never, never>, Record<never, never>>,
    '/posts/20250617': RouteRecordInfo<'/posts/20250617', '/posts/20250617', Record<never, never>, Record<never, never>>,
    '/posts/20250626': RouteRecordInfo<'/posts/20250626', '/posts/20250626', Record<never, never>, Record<never, never>>,
    '/posts/20250706': RouteRecordInfo<'/posts/20250706', '/posts/20250706', Record<never, never>, Record<never, never>>,
    '/posts/20250806': RouteRecordInfo<'/posts/20250806', '/posts/20250806', Record<never, never>, Record<never, never>>,
    '/posts/20250807': RouteRecordInfo<'/posts/20250807', '/posts/20250807', Record<never, never>, Record<never, never>>,
    '/posts/20250910': RouteRecordInfo<'/posts/20250910', '/posts/20250910', Record<never, never>, Record<never, never>>,
    '/rip/': RouteRecordInfo<'/rip/', '/rip', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
