/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/': RouteRecordInfo<
      '/collections/',
      '/collections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/offline/': RouteRecordInfo<
      '/collections/offline/',
      '/collections/offline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/offline/1': RouteRecordInfo<
      '/collections/offline/1',
      '/collections/offline/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/': RouteRecordInfo<
      '/collections/rip/',
      '/collections/rip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/1': RouteRecordInfo<
      '/collections/rip/1',
      '/collections/rip/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/10': RouteRecordInfo<
      '/collections/rip/10',
      '/collections/rip/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/11': RouteRecordInfo<
      '/collections/rip/11',
      '/collections/rip/11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/12': RouteRecordInfo<
      '/collections/rip/12',
      '/collections/rip/12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/13': RouteRecordInfo<
      '/collections/rip/13',
      '/collections/rip/13',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/2': RouteRecordInfo<
      '/collections/rip/2',
      '/collections/rip/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/3': RouteRecordInfo<
      '/collections/rip/3',
      '/collections/rip/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/4': RouteRecordInfo<
      '/collections/rip/4',
      '/collections/rip/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/5': RouteRecordInfo<
      '/collections/rip/5',
      '/collections/rip/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/6': RouteRecordInfo<
      '/collections/rip/6',
      '/collections/rip/6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/7': RouteRecordInfo<
      '/collections/rip/7',
      '/collections/rip/7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/8': RouteRecordInfo<
      '/collections/rip/8',
      '/collections/rip/8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/9': RouteRecordInfo<
      '/collections/rip/9',
      '/collections/rip/9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/900': RouteRecordInfo<
      '/collections/rip/900',
      '/collections/rip/900',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/998': RouteRecordInfo<
      '/collections/rip/998',
      '/collections/rip/998',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/rip/999': RouteRecordInfo<
      '/collections/rip/999',
      '/collections/rip/999',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/shadow/': RouteRecordInfo<
      '/collections/shadow/',
      '/collections/shadow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/shadow/1': RouteRecordInfo<
      '/collections/shadow/1',
      '/collections/shadow/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/shadow/2': RouteRecordInfo<
      '/collections/shadow/2',
      '/collections/shadow/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/friends/': RouteRecordInfo<
      '/friends/',
      '/friends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20070503': RouteRecordInfo<
      '/posts/20070503',
      '/posts/20070503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20210614': RouteRecordInfo<
      '/posts/20210614',
      '/posts/20210614',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20211121': RouteRecordInfo<
      '/posts/20211121',
      '/posts/20211121',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220129': RouteRecordInfo<
      '/posts/20220129',
      '/posts/20220129',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220305': RouteRecordInfo<
      '/posts/20220305',
      '/posts/20220305',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220307': RouteRecordInfo<
      '/posts/20220307',
      '/posts/20220307',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220324': RouteRecordInfo<
      '/posts/20220324',
      '/posts/20220324',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220513': RouteRecordInfo<
      '/posts/20220513',
      '/posts/20220513',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220604': RouteRecordInfo<
      '/posts/20220604',
      '/posts/20220604',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220617': RouteRecordInfo<
      '/posts/20220617',
      '/posts/20220617',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220714': RouteRecordInfo<
      '/posts/20220714',
      '/posts/20220714',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220730': RouteRecordInfo<
      '/posts/20220730',
      '/posts/20220730',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20220802': RouteRecordInfo<
      '/posts/20220802',
      '/posts/20220802',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20230219': RouteRecordInfo<
      '/posts/20230219',
      '/posts/20230219',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20230705': RouteRecordInfo<
      '/posts/20230705',
      '/posts/20230705',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20241110': RouteRecordInfo<
      '/posts/20241110',
      '/posts/20241110',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250211': RouteRecordInfo<
      '/posts/20250211',
      '/posts/20250211',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250610': RouteRecordInfo<
      '/posts/20250610',
      '/posts/20250610',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250617': RouteRecordInfo<
      '/posts/20250617',
      '/posts/20250617',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250626': RouteRecordInfo<
      '/posts/20250626',
      '/posts/20250626',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250706': RouteRecordInfo<
      '/posts/20250706',
      '/posts/20250706',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20250924': RouteRecordInfo<
      '/posts/20250924',
      '/posts/20250924',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251026': RouteRecordInfo<
      '/posts/20251026',
      '/posts/20251026',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251031': RouteRecordInfo<
      '/posts/20251031',
      '/posts/20251031',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251101': RouteRecordInfo<
      '/posts/20251101',
      '/posts/20251101',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251104': RouteRecordInfo<
      '/posts/20251104',
      '/posts/20251104',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251112': RouteRecordInfo<
      '/posts/20251112',
      '/posts/20251112',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251128': RouteRecordInfo<
      '/posts/20251128',
      '/posts/20251128',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251130': RouteRecordInfo<
      '/posts/20251130',
      '/posts/20251130',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20251225': RouteRecordInfo<
      '/posts/20251225',
      '/posts/20251225',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20260100': RouteRecordInfo<
      '/posts/20260100',
      '/posts/20260100',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/20260221': RouteRecordInfo<
      '/posts/20260221',
      '/posts/20260221',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/colle/rip': RouteRecordInfo<
      '/posts/colle/rip',
      '/posts/colle/rip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mook/202112': RouteRecordInfo<
      '/posts/mook/202112',
      '/posts/mook/202112',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mook/202212': RouteRecordInfo<
      '/posts/mook/202212',
      '/posts/mook/202212',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mook/202412': RouteRecordInfo<
      '/posts/mook/202412',
      '/posts/mook/202412',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mook/202511': RouteRecordInfo<
      '/posts/mook/202511',
      '/posts/mook/202511',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mook/202512': RouteRecordInfo<
      '/posts/mook/202512',
      '/posts/mook/202512',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/': RouteRecordInfo<
      '/websites/',
      '/websites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.13_@babel+parse_7e17d51c68a667e8b1e3a26ec8f9bdb9/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/collections/index.md': {
      routes:
        | '/collections/'
      views:
        | never
    }
    'pages/collections/offline/index.md': {
      routes:
        | '/collections/offline/'
      views:
        | never
    }
    'pages/collections/offline/1.md': {
      routes:
        | '/collections/offline/1'
      views:
        | never
    }
    'pages/collections/rip/index.md': {
      routes:
        | '/collections/rip/'
      views:
        | never
    }
    'pages/collections/rip/1.md': {
      routes:
        | '/collections/rip/1'
      views:
        | never
    }
    'pages/collections/rip/10.md': {
      routes:
        | '/collections/rip/10'
      views:
        | never
    }
    'pages/collections/rip/11.md': {
      routes:
        | '/collections/rip/11'
      views:
        | never
    }
    'pages/collections/rip/12.md': {
      routes:
        | '/collections/rip/12'
      views:
        | never
    }
    'pages/collections/rip/13.md': {
      routes:
        | '/collections/rip/13'
      views:
        | never
    }
    'pages/collections/rip/2.md': {
      routes:
        | '/collections/rip/2'
      views:
        | never
    }
    'pages/collections/rip/3.md': {
      routes:
        | '/collections/rip/3'
      views:
        | never
    }
    'pages/collections/rip/4.md': {
      routes:
        | '/collections/rip/4'
      views:
        | never
    }
    'pages/collections/rip/5.md': {
      routes:
        | '/collections/rip/5'
      views:
        | never
    }
    'pages/collections/rip/6.md': {
      routes:
        | '/collections/rip/6'
      views:
        | never
    }
    'pages/collections/rip/7.md': {
      routes:
        | '/collections/rip/7'
      views:
        | never
    }
    'pages/collections/rip/8.md': {
      routes:
        | '/collections/rip/8'
      views:
        | never
    }
    'pages/collections/rip/9.md': {
      routes:
        | '/collections/rip/9'
      views:
        | never
    }
    'pages/collections/rip/900.md': {
      routes:
        | '/collections/rip/900'
      views:
        | never
    }
    'pages/collections/rip/998.md': {
      routes:
        | '/collections/rip/998'
      views:
        | never
    }
    'pages/collections/rip/999.md': {
      routes:
        | '/collections/rip/999'
      views:
        | never
    }
    'pages/collections/shadow/index.md': {
      routes:
        | '/collections/shadow/'
      views:
        | never
    }
    'pages/collections/shadow/1.md': {
      routes:
        | '/collections/shadow/1'
      views:
        | never
    }
    'pages/collections/shadow/2.md': {
      routes:
        | '/collections/shadow/2'
      views:
        | never
    }
    'pages/friends/index.md': {
      routes:
        | '/friends/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/20070503.md': {
      routes:
        | '/posts/20070503'
      views:
        | never
    }
    'pages/posts/20210614.md': {
      routes:
        | '/posts/20210614'
      views:
        | never
    }
    'pages/posts/20211121.md': {
      routes:
        | '/posts/20211121'
      views:
        | never
    }
    'pages/posts/20220129.md': {
      routes:
        | '/posts/20220129'
      views:
        | never
    }
    'pages/posts/20220305.md': {
      routes:
        | '/posts/20220305'
      views:
        | never
    }
    'pages/posts/20220307.md': {
      routes:
        | '/posts/20220307'
      views:
        | never
    }
    'pages/posts/20220324.md': {
      routes:
        | '/posts/20220324'
      views:
        | never
    }
    'pages/posts/20220513.md': {
      routes:
        | '/posts/20220513'
      views:
        | never
    }
    'pages/posts/20220604.md': {
      routes:
        | '/posts/20220604'
      views:
        | never
    }
    'pages/posts/20220617.md': {
      routes:
        | '/posts/20220617'
      views:
        | never
    }
    'pages/posts/20220714.md': {
      routes:
        | '/posts/20220714'
      views:
        | never
    }
    'pages/posts/20220730.md': {
      routes:
        | '/posts/20220730'
      views:
        | never
    }
    'pages/posts/20220802.md': {
      routes:
        | '/posts/20220802'
      views:
        | never
    }
    'pages/posts/20230219.md': {
      routes:
        | '/posts/20230219'
      views:
        | never
    }
    'pages/posts/20230705.md': {
      routes:
        | '/posts/20230705'
      views:
        | never
    }
    'pages/posts/20241110.md': {
      routes:
        | '/posts/20241110'
      views:
        | never
    }
    'pages/posts/20250211.md': {
      routes:
        | '/posts/20250211'
      views:
        | never
    }
    'pages/posts/20250610.md': {
      routes:
        | '/posts/20250610'
      views:
        | never
    }
    'pages/posts/20250617.md': {
      routes:
        | '/posts/20250617'
      views:
        | never
    }
    'pages/posts/20250626.md': {
      routes:
        | '/posts/20250626'
      views:
        | never
    }
    'pages/posts/20250706.md': {
      routes:
        | '/posts/20250706'
      views:
        | never
    }
    'pages/posts/20250924.md': {
      routes:
        | '/posts/20250924'
      views:
        | never
    }
    'pages/posts/20251026.md': {
      routes:
        | '/posts/20251026'
      views:
        | never
    }
    'pages/posts/20251031.md': {
      routes:
        | '/posts/20251031'
      views:
        | never
    }
    'pages/posts/20251101.md': {
      routes:
        | '/posts/20251101'
      views:
        | never
    }
    'pages/posts/20251104.md': {
      routes:
        | '/posts/20251104'
      views:
        | never
    }
    'pages/posts/20251112.md': {
      routes:
        | '/posts/20251112'
      views:
        | never
    }
    'pages/posts/20251128.md': {
      routes:
        | '/posts/20251128'
      views:
        | never
    }
    'pages/posts/20251130.md': {
      routes:
        | '/posts/20251130'
      views:
        | never
    }
    'pages/posts/20251225.md': {
      routes:
        | '/posts/20251225'
      views:
        | never
    }
    'pages/posts/20260100.md': {
      routes:
        | '/posts/20260100'
      views:
        | never
    }
    'pages/posts/20260221.md': {
      routes:
        | '/posts/20260221'
      views:
        | never
    }
    'pages/posts/colle/rip.md': {
      routes:
        | '/posts/colle/rip'
      views:
        | never
    }
    'pages/posts/mook/202112.md': {
      routes:
        | '/posts/mook/202112'
      views:
        | never
    }
    'pages/posts/mook/202212.md': {
      routes:
        | '/posts/mook/202212'
      views:
        | never
    }
    'pages/posts/mook/202412.md': {
      routes:
        | '/posts/mook/202412'
      views:
        | never
    }
    'pages/posts/mook/202511.md': {
      routes:
        | '/posts/mook/202511'
      views:
        | never
    }
    'pages/posts/mook/202512.md': {
      routes:
        | '/posts/mook/202512'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'pages/websites/index.md': {
      routes:
        | '/websites/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
